### ISSUE TITLE
Lua Wrapper compilation fail

### ISSUE THREAD

**Issue by ipese** [CoolProp/CoolProp#1549]
Hello,

I am trying to compile on Debian 8.9 Jessie the Lua wrapper of coolprop.
I followed the doc here http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html for building Coolprop without any issue.
When running make in Coolprop/wrappers/Lua I have the issue

In file included from coolprop/capi.c:5:0:
CoolPropLib.h:142:73: error: unknown type name ‘bool’
     EXPORT_CODE void CONVENTION set_config_bool(const char * key, const bool val);

anything is missing ?

**Comment by ibell** [comment]
Can you please provide a complete build log showing all the steps that you
did at the console?

**Comment by ipese** [comment]
git clone https://github.com/CoolProp/CoolProp --recursive
...
cd CoolProp
mkdir build && cd build
cmake .. -DCOOLPROP_SHARED_LIBRARY=ON -DCMAKE_BUILD_TYPE=Release
...
cmake --build .
...
cd ../wrappers/Lua
make
cc -std=c99 -pedantic-errors -fPIC -I/usr/include/lua5.2   -g -O2 -Wall -Wextra -Wswitch-enum -Wwrite-strings -Wshadow -c -o coolprop/capi.o coolprop/capi.c
In file included from coolprop/capi.c:5:0:
coolprop/../../../include/CoolPropLib.h:142:73: error: unknown type name ‘bool’
     EXPORT_CODE void CONVENTION set_config_bool(const char * key, const bool val);
                                                                         ^
lualib.mk:86: recipe for target 'coolprop/capi.o' failed
make: *** [coolprop/capi.o] Error 1

exactly as suggested in the tuto here http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html and in the README here https://github.com/CoolProp/CoolProp/tree/master/wrappers/Lua

**Comment by ibell** [comment]
Looks like a classical c/c++ clash.  Not sure how this ever worked...

**Comment by ibell** [comment]
Hmm this was done before we added the set_config_bool function to the API.
Can you try a typedef from bool to short?  C doesn't do bool.  That should
work.  Here's more on that idea: https://stackoverflow.com/a/1921557/1360263

**Comment by homoprogramus** [comment]
It compiles and install (make, make install) but when running the example (lua example.lua) I have
lua: error loading module 'coolprop.capi' from file '/usr/lib/x86_64-linux-gnu/lua/5.2/coolprop/capi.so':
	/usr/lib/x86_64-linux-gnu/lua/5.2/coolprop/capi.so: undefined symbol: saturation_ancillary
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.2/coolprop.lua:14: in main chunk
	[C]: in function 'require'
	example.lua:1: in main chunk
	[C]: in ?

objdump -TC capi.so gives me
capi.so:     file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000000  w   D  *UND*	0000000000000000              _ITM_deregisterTMCloneTable
0000000000000000      D  *UND*	0000000000000000              luaL_setfuncs
0000000000000000      D  *UND*	0000000000000000              saturation_ancillary
0000000000000000      D  *UND*	0000000000000000              HAPropsSI
0000000000000000      D  *UND*	0000000000000000              redirect_stdout
0000000000000000      D  *UND*	0000000000000000              lua_createtable
0000000000000000      D  *UND*	0000000000000000              luaL_checknumber
0000000000000000      D  *UND*	0000000000000000              PropsSI
0000000000000000      D  *UND*	0000000000000000              set_reference_stateD
0000000000000000      D  *UND*	0000000000000000              lua_pushinteger
0000000000000000      D  *UND*	0000000000000000              set_debug_level
0000000000000000      D  *UND*	0000000000000000              luaL_checklstring
0000000000000000      D  *UND*	0000000000000000              K2F
0000000000000000      D  *UND*	0000000000000000              get_parameter_information_string
0000000000000000      D  *UND*	0000000000000000              luaL_checkinteger
0000000000000000  w   D  *UND*	0000000000000000              __gmon_start__
0000000000000000      D  *UND*	0000000000000000              lua_pushnumber
0000000000000000      D  *UND*	0000000000000000              lua_pushboolean
0000000000000000      D  *UND*	0000000000000000              get_debug_level
0000000000000000      D  *UND*	0000000000000000              get_global_param_string
0000000000000000      D  *UND*	0000000000000000              set_reference_stateS
0000000000000000      D  *UND*	0000000000000000              Props1SI
0000000000000000  w   D  *UND*	0000000000000000              _Jv_RegisterClasses
0000000000000000      D  *UND*	0000000000000000              F2K
0000000000000000      D  *UND*	0000000000000000              get_fluid_param_string
0000000000000000  w   D  *UND*	0000000000000000              _ITM_registerTMCloneTable
0000000000000000      D  *UND*	0000000000000000              get_param_index
0000000000000000      D  *UND*	0000000000000000              lua_pushstring
0000000000000000  w   DF *UND*	0000000000000000  GLIBC_2.2.5 __cxa_finalize
0000000000000000      D  *UND*	0000000000000000              PhaseSI
0000000000202250 g    D  .data	0000000000000000  Base        _edata
0000000000202258 g    D  .bss	0000000000000000  Base        _end
0000000000202250 g    D  .bss	0000000000000000  Base        __bss_start
0000000000000e68 g    DF .init	0000000000000000  Base        _init
00000000000017b8 g    DF .fini	0000000000000000  Base        _fini
0000000000001790 g    DF .text	0000000000000028  Base        luaopen_coolprop_capi

Is there a missing linking library in the compile command called by make ?
cc -std=c99 -pedantic-errors -fPIC -I/usr/include/lua5.2   -g -O2 -Wall -Wextra -Wswitch-enum -Wwrite-strings -Wshadow -c -o coolprop/capi.o coolprop/capi.c

**Comment by ibell** [comment]
Can you point me to an example of making a lua program that calls
CoolProp?  I've no experience with Lua, so without that, it'll be tough for
me to debug

**Comment by homoprogramus** [comment]
There is an example in the coolprop folder CoolProp/wrapper/Lua/example.lua

local cp = require "coolprop"

print[[
Information Examples
====================
]]
print("Version", cp.version())
print("gitrevision", cp.gitrevision())
print("FluidsList", cp.FluidsList())
print("Debug Level", cp.get_debug_level())
print()

it crashes at line 1 when importing the coolprop.lua which in turn try to load capi.so at line 14

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
