### ISSUE TITLE
Unable to compile with fmt 10.0.0

### ISSUE THREAD

**Issue by FtZPetruska** [CoolProp/CoolProp#2251]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

Using the latest version of fmt (10.0.0), compilation fails on all platforms due to breaking changes. (See https://github.com/microsoft/vcpkg/pull/31378)

### Steps to Reproduce

1. Install fmt 10.0.0
2. Compile CoolProp 6.4.3

**Expected behavior:** Compilation succeeds

**Actual behavior:** Compilation fails with the following message:

```
D:\installed\x64-windows\include\fmt\core.h(1691): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'
D:\installed\x64-windows\include\fmt\core.h(1711): note: see reference to function template instantiation 'fmt::v10::detail::value<Context> fmt::v10::detail::make_value<Context,const CoolProp::input_pairs&>(T)' being compiled
        with
        [
            Context=context,
            T=const CoolProp::input_pairs &
        ]
```

### Versions

**CoolProp Version:** 6.4.3
**Operating System and Version:** vcpkg CI runners (Windows, macOS, Linux)
**Access Method:** N/A

### Additional Information

The changelog for fmt [10.0.0](https://github.com/fmtlib/fmt/releases/tag/10.0.0) contains:

```
Removed deprecated implicit conversions for enums and conversions to primitive types for compatibility with std::format and to prevent potential ODR violations. Use format_as instead.
```

The compilation error seems related to this change as `CoolProp::input_pairs` is an enum.

A `format_as` overload should be provided for every enum that needs to be formatted, such as:

```cpp
#include <fmt/format.h>

enum class Foo {
    BAR = 0
};

auto format_as(Foo f) { return fmt::underlying(f); }
```

**Comment by ibell** [comment]
You are invited to make a PR including the updated fmtlib submodule and
changes to the source required.
