### ISSUE TITLE
iOS compilation

### ISSUE THREAD

**Issue by babaksamareh** [CoolProp/CoolProp#600]
Hello guys,
I'm trying to compile the new version (5.0.8) for iOS. I get the .a libraries and everything is ok. But when I plug them into my code which was running with version 5.0.something, it does not work and I get this error:

Undefined symbols for architecture x86_64:
  "CoolProp::BicubicBackend::build_coeffs(CoolProp::SinglePhaseGriddedTableData&, std::__1::vector<std::__1::vector<CoolProp::CellCoeffs, std::__1::allocator<CoolProp::CellCoeffs> >, std::__1::allocator<std::__1::vector<CoolProp::CellCoeffs, std::__1::allocator<CoolProp::CellCoeffs> > > >&)", referenced from:
      CoolProp::BicubicBackend::BicubicBackend(std::__1::shared_ptr<CoolProp::AbstractState>) in libCoolPropSIM.a(AbstractState.o)
  "vtable for CoolProp::TTSEBackend", referenced from:
      CoolProp::TTSEBackend::TTSEBackend(std::__1::shared_ptr<CoolProp::AbstractState>) in libCoolPropSIM.a(AbstractState.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for CoolProp::BicubicBackend", referenced from:
      CoolProp::BicubicBackend::BicubicBackend(std::__1::shared_ptr<CoolProp::AbstractState>) in libCoolPropSIM.a(AbstractState.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea?

Thanks,

**Comment by ibell** [comment]
Have you tried compiling from the github sources?  I've not seen that sort
of error before, and I wonder if the 5.0.8 wasn't broken in some way that
is important for you.

**Comment by ibell** [comment]
Let me guess, you are on 10.10 as well?

**Comment by babaksamareh** [comment]
Well yes I'm on 10.10. Here is an update. I compiled the older version that I had again. It does not work! Now I get this error:

Undefined symbols for architecture x86_64:
  "CoolProp::get_global_param_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      -[ViewController calcButtonPres:] in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have this line in my code:

 std::string CPError;
 CPError   = CoolProp::get_global_param_string("errstring");

When I comment this line, everything works just fine. What's wrong with 10.10?

**Comment by jowr** [comment]
There is nothing wrong, but they changed the C++ standard libraries and i guess that this is what also causes headache here...

**Comment by ibell** [comment]
Did it work in 10.9?

**Comment by babaksamareh** [comment]
Yep it was working just fine. Actually if I use the .a file from 10.9 it still works just fine. If I compile it again, it does not!

**Comment by babaksamareh** [comment]
Well, for now I can stick to the old .a file that I have. I want to use the HAProps function but it seems that I don't have it. When I type CoolProp:: I have PropsSI and other functions, but no HAProps! Is there another code that I need to compile for HAProps?

**Comment by ibell** [comment]
How about HumidAirProp::HAPropsSI?    We don't keep it in the main namespace.

**Comment by babaksamareh** [comment]
I'm an idiot. Had totally forgotten to import the header file for HumidAir.
So this is solved. However, lets keep this issue open. I'm working on implementing the new version on iOS. I'll post my findings here.

**Comment by ibell** [comment]
Yes, if you'll notice, 4 of the open issues are related to 10.10 - a major
pain in my neck right now

**Comment by babaksamareh** [comment]
UPDATE: It does work on 10.10. I was using the previous xCode project to compile the new version. What I didn't notice was that the new version has some extra files that are not being compiled with the rest of the project. So, I started a new project, with the same steps as reported in iOS wrapper page, and voila, it works like a charm.

**Comment by ibell** [comment]
*phew* Thanks for the report
