### ISSUE TITLE
Fortran wrapper on Win...still unable to run it!

### ISSUE THREAD

**Issue by EmiCas** [CoolProp/CoolProp#909]
Dear all, I'm following the suggested procedure to compile a static library of CoolProp and link it with my FORTRAN code. I tried MinGW but (as anticipated in a warning) did not work. I thus tried with the TDM-GCC distribution (carrying the GCC 5.1 version) but still this did not work. I therefore tried with the GCC 5.2 distribution shipped with Simply Fortran, which is the tool I'm planning to adopt (in order to avoid the cumbersome installation of Visual Studio). This worked, meaning that after executing the following suggested commands:
**********************************************************************************
git clone https://github.com/CoolProp/CoolProp --recursive
cd CoolProp
mkdir build && cd build
mkdir gccstatic && cd gccstatic
cmake ../.. -G "MinGW Makefiles" -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_EXTERNC_LIBRARY=ON -DCMAKE_VERBOSE_MAKEFILE=ON
cmake --build .
**********************************************************************************
I finally was able to build the libCoolProp.a, without getting noticed of any error (nice !).
I thus tried to run the suggested example in CoolProp\wrappers\Fortran\detailed_example.
By issuing the command
**********************************************************************************
gfortran -c -Wall cpinterface.f90 cool_fortran_bind.f90
********************************************************************************** 
I get the cool_fortran_bind.o and cpinterface.o and cpinterface.mod created (nice !)
thus if I continue by issuing the command
**********************************************************************************
gcc -o main *.o libCoolProp.a -lstdc++ -lgfortran
**********************************************************************************
I get in the troubles that, up to now, proved endless...
You can see the output in the text below, copied from the prompt!

**********************************************************************************
C:\CoolProp\wrappers\Fortran\detailed_example>gcc -o main *.o libCoolProp.a -lstdc++ -lgfortran
cool_fortran_bind.o:cool_fortran_bind.f90:(.text+0x19d): undefined reference to `PropsSI'
cool_fortran_bind.o:cool_fortran_bind.f90:(.text+0x1e9): undefined reference to `PropsSI'
c:/program files (x86)/simply fortran 2/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cool_fortran_bind.o: bad reloc address 0x0 in section `.pdata'
c:/program files (x86)/simply fortran 2/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status

C:\CoolProp\wrappers\Fortran\detailed_example>
**********************************************************************************

I must admit I'm not a programming guru, and I'm probably overlooking some stupid detail...I hope and trust you will be able to solve these problems! thanks in advance.

Emiliano

**Comment by ibell** [comment]
You can't mix and match compiler stacks usually.  If you start with tdm
gcc, you should use that all the way through.  I can try later on my
computer.

**Comment by EmiCas** [comment]
Hi Ian,
Thanks for your prompt reply!
I’m afraid I do not fully understand what you mean...I have tried TDM but then (since it was not working) shifted to GCC 5.2 (shipped with Simply Fortran) starting from the beginning.
With this I was able to build the library but got stuck soon after ☹
I do not think I’ve mixed anything...

Let me know, thanks again

Emiliano

**Comment by ibell** [comment]
What didn't work with tdm version 5.1?  That's what I use.

**Comment by EmiCas** [comment]
I have to retry with TDM, give me a sec...I focused on GCC 5.2 since I intended to use Simply Fortran afterwards, but maybe I was too optimistic about the whole story...

**Comment by ibell** [comment]
It will work, but can't fix bugs we dont know about

**Comment by ibell** [comment]
Ok, I tried it myself, and it worked, but I had to specify the bitness (32-bit or 64-bit).  Different parts default to either 32-bit or 64-bit compilation.

It works in our testing, both in 32-bit and 64-bit on windows:

http://www.coolprop.dreamhosters.com:8010/builders/Fortran-executable-windows-32bit-GCC-ExternC/builds/45
http://www.coolprop.dreamhosters.com:8010/builders/Fortran-executable-windows-64bit-GCC-ExternC/builds/54

That might give you some insight as well.

**Comment by ibell** [comment]
In order to ensure that you have 64-bit throughout, you could do:

```
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_EXTERNC_LIBRARY=ON -DFORCE_BITNESS_64=ON -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
cmake --build .
gfortran -c -Wall cpinterface.f90 cool_fortran_bind.f90 -m64
gcc -o main cpinterface.o cool_fortran_bind.o libCoolProp.a -lstdc++ -lgfortran -m64
```

**Comment by ibell** [comment]
That should work.  If not, please provide the entire build log.

**Comment by EmiCas** [comment]
Hey Ian, thanks a lot for your support. I just missed one thing: are u referring now to the TDM (GCC 5.1) or the SimplyFortran GCC 5.2 compilers ?

**Comment by ibell** [comment]
I'm using 5.1.

**Comment by EmiCas** [comment]
ok, I proceed with 5.1 then. thanks

**Comment by EmiCas** [comment]
Nope, I am not able to have it running...where can I find the build log I should send you?

**Comment by ibell** [comment]
You can drop it in the issue.  Put it in triple back ticks.

**Comment by EmiCas** [comment]
Sorry I was not clear...where is the build log I am supposed to send you? in which folder is generated?
thanks

**Comment by ibell** [comment]
In the command prompt window.  You can select all, then paste into github.

**Comment by EmiCas** [comment]
```C:\>cd CoolProp

C:\CoolProp>cd build

C:\CoolProp\build>cd gccstatic

C:\CoolProp\build\gccstatic>cmake ../.. -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_
EXTERNC_LIBRARY=ON -DFORCE_BITNESS_64=ON -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE
=Release
-- COOLPROP_INSTALL_PREFIX=C:/CoolProp/install_root
-- CoolProp version: 5.1.2dev
-- Setting bitness flag -m32
-- Library compilation detected:
-- Creating CoolProp, a 32-bit library with Release settings
-- CMAKE_SYSTEM_NAME: Windows
-- COOLPROP_STATIC_LIBRARY: ON
-- COOLPROP_SHARED_LIBRARY: OFF
-- COOLPROP_OBJECT_LIBRARY: OFF
-- CONVENTION:
-- COOLPROP_LIBRARY_HEADER: include/CoolPropLib.h
-- COOLPROP_LIBRARY_SOURCE: src/CoolPropLib.cpp
-- COMPILE_FLAGS:  -DEXTERNC -m32
-- LINK_FLAGS:  -m32
-- Configuring done
-- Generating done
-- Build files have been written to: C:/CoolProp/build/gccstatic

C:\CoolProp\build\gccstatic>cmake --build .
cpversion.h is up to date
version written to hidden file: C:\CoolProp\.version for use in builders that do
n't use git repo
git version 2.6.4.windows.1
git is accessible at the command line
git revision is ebf32a8b94af9d3488167787dd4483d49adc25f9
gitrevision.h is up to date
all_fluids_JSON.h is up to date
all_incompressibles_JSON.h is up to date
mixture_departure_functions_JSON.h is up to date
mixture_binary_pairs_JSON.h is up to date
predefined_mixtures_JSON.h is up to date
[  0%] Built target generate_headers
[  2%] Building CXX object CMakeFiles/CoolProp.dir/src/AbstractState.cpp.obj
In file included from C:/CoolProp/externals/Eigen/Eigen/Core:287:0,
                 from C:/CoolProp/include/Helmholtz.h:7,
                 from C:/CoolProp/include/CoolPropFluid.h:12,
                 from C:\CoolProp\src\Backends/Helmholtz/HelmholtzEOSMixtureBack
end.h:6,
                 from C:\CoolProp\src\Backends/Helmholtz/HelmholtzEOSBackend.h:1
2,
                 from C:\CoolProp\src\AbstractState.cpp:14:
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h: In function 'void* Eig
en::internal::aligned_malloc(std::size_t)':
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h:228:53: error: '_aligne
d_malloc' was not declared in this scope
     result = _aligned_malloc(size, EIGEN_ALIGN_BYTES);
                                                     ^
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h: In function 'void Eige
n::internal::aligned_free(void*)':
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h:251:22: error: '_aligne
d_free' was not declared in this scope
     _aligned_free(ptr);
                      ^
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h: In function 'void* Eig
en::internal::aligned_realloc(void*, std::size_t, std::size_t)':
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h:283:59: error: '_aligne
d_realloc' was not declared in this scope
   result = _aligned_realloc(ptr,new_size,EIGEN_ALIGN_BYTES);
                                                           ^
CMakeFiles\CoolProp.dir\build.make:62: recipe for target 'CMakeFiles/CoolProp.di
r/src/AbstractState.cpp.obj' failed
mingw32-make.exe[2]: *** [CMakeFiles/CoolProp.dir/src/AbstractState.cpp.obj] Err
or 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/CoolProp.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

C:\CoolProp\build\gccstatic>```

**Comment by ibell** [comment]
Please clear out your gccstatic directory and start again.

**Comment by EmiCas** [comment]
Dear Ian, good morning. I've cleaned the folder and started over.
I report here first the attempt with bitness forced to 64 and then to 32 (gccstatic directory cleaned in between). The output are different even though both fail.
I hope it helps!
Have a nice day
```
C:\CoolProp\build\gccstatic>cmake ../.. -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_
EXTERNC_LIBRARY=ON -DFORCE_BITNESS_64=ON -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE
=Release
-- COOLPROP_INSTALL_PREFIX=C:/CoolProp/install_root
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: C:/TDM-GCC-32/bin/gcc.exe
-- Check for working C compiler: C:/TDM-GCC-32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/TDM-GCC-32/bin/g++.exe
-- Check for working CXX compiler: C:/TDM-GCC-32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 5.1.2dev
-- Found PythonInterp: C:/Python27/python.exe (found suitable version "2.7.8", m
inimum required is "2.7")
-- Setting bitness flag -m64
-- Library compilation detected:
-- Creating CoolProp, a 64-bit library with Release settings
-- CMAKE_SYSTEM_NAME: Windows
-- COOLPROP_STATIC_LIBRARY: ON
-- COOLPROP_SHARED_LIBRARY: OFF
-- COOLPROP_OBJECT_LIBRARY: OFF
-- CONVENTION:
-- COOLPROP_LIBRARY_HEADER: include/CoolPropLib.h
-- COOLPROP_LIBRARY_SOURCE: src/CoolPropLib.cpp
-- COMPILE_FLAGS:  -DEXTERNC -m64
-- LINK_FLAGS:  -m64
-- Configuring done
-- Generating done
-- Build files have been written to: C:/CoolProp/build/gccstatic

C:\CoolProp\build\gccstatic>cmake --build .
Scanning dependencies of target generate_headers
cpversion.h is up to date
version written to hidden file: C:\CoolProp\.version for use in builders that do
n't use git repo
git version 2.6.4.windows.1
git is accessible at the command line
git revision is ebf32a8b94af9d3488167787dd4483d49adc25f9
gitrevision.h is up to date
all_fluids_JSON.h is up to date
all_incompressibles_JSON.h is up to date
mixture_departure_functions_JSON.h is up to date
mixture_binary_pairs_JSON.h is up to date
predefined_mixtures_JSON.h is up to date
[  0%] Built target generate_headers
Scanning dependencies of target CoolProp
[  2%] Building CXX object CMakeFiles/CoolProp.dir/src/AbstractState.cpp.obj
C:\CoolProp\src\AbstractState.cpp:1:0: sorry, unimplemented: 64-bit mode not com
piled in
 /*
 ^
CMakeFiles\CoolProp.dir\build.make:62: recipe for target 'CMakeFiles/CoolProp.di
r/src/AbstractState.cpp.obj' failed
mingw32-make.exe[2]: *** [CMakeFiles/CoolProp.dir/src/AbstractState.cpp.obj] Err
or 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/CoolProp.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```

Here with 32:
```
C:\CoolProp\build\gccstatic>cmake ../.. -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_
EXTERNC_LIBRARY=ON -DFORCE_BITNESS_32=ON -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE
=Release
-- COOLPROP_INSTALL_PREFIX=C:/CoolProp/install_root
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: C:/TDM-GCC-32/bin/gcc.exe
-- Check for working C compiler: C:/TDM-GCC-32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/TDM-GCC-32/bin/g++.exe
-- Check for working CXX compiler: C:/TDM-GCC-32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 5.1.2dev
-- Found PythonInterp: C:/Python27/python.exe (found suitable version "2.7.8", m
inimum required is "2.7")
-- Setting bitness flag -m32
-- Library compilation detected:
-- Creating CoolProp, a 32-bit library with Release settings
-- CMAKE_SYSTEM_NAME: Windows
-- COOLPROP_STATIC_LIBRARY: ON
-- COOLPROP_SHARED_LIBRARY: OFF
-- COOLPROP_OBJECT_LIBRARY: OFF
-- CONVENTION:
-- COOLPROP_LIBRARY_HEADER: include/CoolPropLib.h
-- COOLPROP_LIBRARY_SOURCE: src/CoolPropLib.cpp
-- COMPILE_FLAGS:  -DEXTERNC -m32
-- LINK_FLAGS:  -m32
-- Configuring done
-- Generating done
-- Build files have been written to: C:/CoolProp/build/gccstatic

C:\CoolProp\build\gccstatic>cmake --build .
Scanning dependencies of target generate_headers
cpversion.h is up to date
version written to hidden file: C:\CoolProp\.version for use in builders that do
n't use git repo
git version 2.6.4.windows.1
git is accessible at the command line
git revision is ebf32a8b94af9d3488167787dd4483d49adc25f9
gitrevision.h is up to date
all_fluids_JSON.h is up to date
all_incompressibles_JSON.h is up to date
mixture_departure_functions_JSON.h is up to date
mixture_binary_pairs_JSON.h is up to date
predefined_mixtures_JSON.h is up to date
[  0%] Built target generate_headers
Scanning dependencies of target CoolProp
[  2%] Building CXX object CMakeFiles/CoolProp.dir/src/AbstractState.cpp.obj
In file included from C:/CoolProp/externals/Eigen/Eigen/Core:287:0,
                 from C:/CoolProp/include/Helmholtz.h:7,
                 from C:/CoolProp/include/CoolPropFluid.h:12,
                 from C:\CoolProp\src\Backends/Helmholtz/HelmholtzEOSMixtureBack
end.h:6,
                 from C:\CoolProp\src\Backends/Helmholtz/HelmholtzEOSBackend.h:1
2,
                 from C:\CoolProp\src\AbstractState.cpp:14:
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h: In function 'void* Eig
en::internal::aligned_malloc(std::size_t)':
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h:228:53: error: '_aligne
d_malloc' was not declared in this scope
     result = _aligned_malloc(size, EIGEN_ALIGN_BYTES);
                                                     ^
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h: In function 'void Eige
n::internal::aligned_free(void*)':
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h:251:22: error: '_aligne
d_free' was not declared in this scope
     _aligned_free(ptr);
                      ^
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h: In function 'void* Eig
en::internal::aligned_realloc(void*, std::size_t, std::size_t)':
C:/CoolProp/externals/Eigen/Eigen/src/Core/util/Memory.h:283:59: error: '_aligne
d_realloc' was not declared in this scope
   result = _aligned_realloc(ptr,new_size,EIGEN_ALIGN_BYTES);
                                                           ^
CMakeFiles\CoolProp.dir\build.make:62: recipe for target 'CMakeFiles/CoolProp.di
r/src/AbstractState.cpp.obj' failed
mingw32-make.exe[2]: *** [CMakeFiles/CoolProp.dir/src/AbstractState.cpp.obj] Err
or 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/CoolProp.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

C:\CoolProp\build\gccstatic>```

**Comment by ibell** [comment]
Couple of issues:
A) as it states in the error message, you installed a 32bit version of tdm GCC, can you install the 64 bit one?
B) this setup works fine for me on windows.  Are you using the most up to date version of the code?  What version/revision are you at?

**Comment by EmiCas** [comment]
Dear Ian, thanks for your support and best wishes for this new 2016!
I tried to install the 64 version of tdm GCC and the library was built smoothly without errors!
I then tried to run the example but got the following: 
```
C:\CoolProp\wrappers\Fortran\detailed_example>gfortran -c -Wall cpinterface.f90
cool_fortran_bind.f90

C:\CoolProp\wrappers\Fortran\detailed_example>gcc -o main *.o libCoolProp.a -lst
dc++ -lgfortran
gcc: error: *.o: Invalid argument
```
If I input all the files names it works smoothly: 
```
C:\CoolProp\wrappers\Fortran\detailed_example>gcc -o main cool_fortran_bind.o cp
interface.o libCoolProp.a -lstdc++ -lgfortran

C:\CoolProp\wrappers\Fortran\detailed_example>main
   489.44737525195853        489.44737525195853
```
However, this makes the procedure clearly cumbersome...it looks like the wildcard *.o is not supported. I found little help online, have you encountered this already? what would you suggest?

**Comment by ibell** [comment]
Glad to hear you got things working.  I'll update the docs to recommend
TDM-GCC instead of MINGW and close this issue. Any other
issues/recommendations for/with the docs?

Simply put - globbing (*.f90) is not supported in conventional command
prompt in MINGW (TDM or otherwise).  It should work in powershell I
believe.  In any case, you are right.  Nothing we can do about that.  I
hardcode paths.  Or you could construct the name of .o files using some
magic in a batch file.

**Comment by EmiCas** [comment]
perfect! I think the procedures outlined in the website (docs, etc.) are very clear !
as for globbing, I believe it is a GCC issue which does not support it, I'll try filing a support request.

have a nice day
