### ISSUE TITLE
Bug in AbstractState.pyx (aka can't build or install CoolProp python wrapper for python 3.6 under linux)

### ISSUE THREAD

**Issue by notmyrealhandle** [CoolProp/CoolProp#1638]
arg1 and arg2 used with the fused type string_or_size_t in AbstractState.pyx do not match CAS1 and CAS2 used in AbstractState.pyd.

Using:

patch < [AbstractState.patch](https://gist.github.com/notmyrealhandle/77a2c04516aa235eeae928e628f20b01)

in the directory: CoolProp/wrappers/Python/CoolProp

resolves this for me.  Verified with:

import CoolProp.CoolProp as CP
CAS_He = CP.get_fluid_param_string('Helium','CAS')
CAS_Xe = CP.get_fluid_param_string('Xe','CAS')
CP.apply_simple_mixing_rule(CAS_He, CAS_Xe, 'linear')
AS = CP.AbstractState("HEOS","Helium&Xenon")
AS.set_binary_interaction_double(0, 1, 'betaT', 0.987)
AS.get_binary_interaction_double(0, 1, 'betaT')

Out[7]: 0.987

And now the bugreport:

Environment:
lubuntu 17.10 (artful) on a dell e6220: 
uname: 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
gcc --version: gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0
python 3.6.4 in a pyenv virtual env

After 

git clone https://github.com/CoolProp/CoolProp.git --recursive

and

cd CoolProp/wrappers/Python/

python setup.py install 

will fail with the most helpful and easiest to debug error output I have ever come across:

version written to file: /home/ul/.local/src/CoolProp/include/cpversion.h
version written to hidden file: /home/ul/.local/src/CoolProp/.version for use in builders that don't use git repo
git version 2.14.1
git is accessible at the command line
git revision is d394aa1968ad59c6afd9153b353d4acb18cfffa2
*** Generating gitrevision.h ***
/home/ul/.local/src/CoolProp/include/gitrevision.h written to file
/home/ul/.local/src/CoolProp/include/all_fluids_JSON.h written to file
/home/ul/.local/src/CoolProp/include/all_incompressibles_JSON.h written to file
/home/ul/.local/src/CoolProp/include/mixture_departure_functions_JSON.h written to file
/home/ul/.local/src/CoolProp/include/mixture_binary_pairs_JSON.h written to file
/home/ul/.local/src/CoolProp/include/predefined_mixtures_JSON.h written to file
/home/ul/.local/src/CoolProp/include/all_cubics_JSON.h written to file
/home/ul/.local/src/CoolProp/include/cubic_fluids_schema_JSON.h written to file
****** Writing the constants module ******
Cython will be used; cy_ext is pyx
../../include --> CoolProp/include
removing CoolProp/include/cubic_fluids_schema_JSON.h
removing CoolProp/include/all_incompressibles_JSON.h
removing CoolProp/include/mixture_binary_pairs_JSON.h
removing CoolProp/include/all_fluids_JSON.h
removing CoolProp/include/mixture_departure_functions_JSON.h
removing CoolProp/include/all_cubics_JSON.h
removing CoolProp/include/predefined_mixtures_JSON.h
../../externals/cppformat/fmt --> CoolProp/include/fmt
../../CoolPropBibTeXLibrary.bib --> CoolProp/CoolPropBibTeXLibrary.bib
files copied.
Compiling CoolProp/CoolProp.pyx because it changed.
Compiling CoolProp/_constants.pyx because it changed.
[1/2] Cythonizing CoolProp/CoolProp.pyx
warning: CoolProp/AbstractState.pyx:70:10: Obtaining 'char *' from externally modifiable global Python value
warning: CoolProp/AbstractState.pyx:70:10: Obtaining 'char *' from externally modifiable global Python value
warning: CoolProp/AbstractState.pyx:76:10: Obtaining 'char *' from externally modifiable global Python value
warning: CoolProp/AbstractState.pyx:76:10: Obtaining 'char *' from externally modifiable global Python value
warning: CoolProp/AbstractState.pyx:83:10: Obtaining 'char *' from externally modifiable global Python value
warning: CoolProp/AbstractState.pyx:83:10: Obtaining 'char *' from externally modifiable global Python value
Traceback (most recent call last):
  File "setup.py", line 317, in <module>
    ext_modules = cythonize(ext_modules, compiler_directives = cython_directives)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
    cythonize_one(*args)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1144, in cythonize_one
    result = compile([pyx_file], options)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 695, in compile
    return compile_multiple(source, options)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 673, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
    data = run(phase, data)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
    return phase(data)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 141, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 373, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 4715, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 428, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/FusedNode.py", line 840, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1910, in generate_function_definitions
    self.generate_argument_parsing_code(env, code)
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 2576, in generate_argument_parsing_code
    put_into_closure(scope.lookup_here(arg.name))
  File "/home/ul/.pyenv/versions/p364.0/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 2571, in put_into_closure
    if entry.in_closure and not arg.default:
AttributeError: 'NoneType' object has no attribute 'in_closure'
 
In case you are wondering...

pip install coolprop 

tries to install coolprop 6.0.0 and fails with yet another incredibly helpful error output:

Collecting coolprop
  Using cached CoolProp-6.0.0.tar.gz
Building wheels for collected packages: coolprop
  Running setup.py bdist_wheel for coolprop ... error
  Complete output from command /home/ul/.pyenv/versions/3.6.4/envs/p364.0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-81hghapn/coolprop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpiushqdlvpip-wheel- --python-tag cp36:
  Cython will not be used; cy_ext is cpp
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/__init__.py -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/State.py -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/constants.py -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/HumidAirProp.py -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/BibtexParser.py -> build/lib.linux-x86_64-3.6/CoolProp
  creating build/lib.linux-x86_64-3.6/CoolProp/tests
  copying CoolProp/tests/__init__.py -> build/lib.linux-x86_64-3.6/CoolProp/tests
  copying CoolProp/tests/test_Props.py -> build/lib.linux-x86_64-3.6/CoolProp/tests
  copying CoolProp/tests/runner.py -> build/lib.linux-x86_64-3.6/CoolProp/tests
  copying CoolProp/tests/test_plots.py -> build/lib.linux-x86_64-3.6/CoolProp/tests
  copying CoolProp/tests/test_CoolPropState.py -> build/lib.linux-x86_64-3.6/CoolProp/tests
  creating build/lib.linux-x86_64-3.6/CoolProp/GUI
  copying CoolProp/GUI/__init__.py -> build/lib.linux-x86_64-3.6/CoolProp/GUI
  copying CoolProp/GUI/CoolPropGUI.py -> build/lib.linux-x86_64-3.6/CoolProp/GUI
  copying CoolProp/GUI/PsychScript.py -> build/lib.linux-x86_64-3.6/CoolProp/GUI
  creating build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/psy.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/SimpleCycles.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/__init__.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/ConsistencyPlots.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/PsychChart.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/Common.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/Tests.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/Plots.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/Plots/PsychScript.py -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  copying CoolProp/constants_header.pxd -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/AbstractState.pxd -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/State.pxd -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/typedefs.pxd -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/cAbstractState.pxd -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/CoolProp.pxd -> build/lib.linux-x86_64-3.6/CoolProp
  copying CoolProp/Plots/psyrc -> build/lib.linux-x86_64-3.6/CoolProp/Plots
  running build_ext
  building 'CoolProp.CoolProp' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/CoolProp
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/Tests
  creating build/temp.linux-x86_64-3.6/src/Backends
  creating build/temp.linux-x86_64-3.6/src/Backends/REFPROP
  creating build/temp.linux-x86_64-3.6/src/Backends/Helmholtz
  creating build/temp.linux-x86_64-3.6/src/Backends/Helmholtz/Fluids
  creating build/temp.linux-x86_64-3.6/src/Backends/Cubics
  creating build/temp.linux-x86_64-3.6/src/Backends/IF97
  creating build/temp.linux-x86_64-3.6/src/Backends/Tabular
  creating build/temp.linux-x86_64-3.6/src/Backends/Incompressible
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I./include -I./src -I./externals/Eigen -I./externals/msgpack-c/include -I/home/ul/.pyenv/versions/3.6.4/envs/p364.0/include -I/home/ul/.pyenv/versions/3.6.4/include/python3.6m -c CoolProp/CoolProp.cpp -o build/temp.linux-x86_64-3.6/CoolProp/CoolProp.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:0,
                   from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7,
                   from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                   from /home/ul/.pyenv/versions/3.6.4/include/python3.6m/Python.h:11,
                   from CoolProp/CoolProp.cpp:4:
  ./externals/cppformat/cppformat/format.h: In member function ‘void fmt::internal::ArgFormatterBase<Impl, Char>::visit_char(int)’:
  ./externals/cppformat/cppformat/format.h:1750:20: error: expected unqualified-id before numeric constant
       const unsigned CHAR_WIDTH = 1;
                      ^
... (remainder of error output truncated)

I think due to this bug (note gcc --version at top of post):
- https://github.com/fmtlib/fmt/issues/398

Note:
- https://github.com/CoolProp/CoolProp/issues/1309 is not helpful.

**Comment by ibell** [comment]
Hmm that's weird.  I compile with python 3.6 all the time without
problems.  What version of cython do you use? Maybe they introduced a bug
in the fused types?

Can you format your patch as a pull request on GitHub?  If so, that would
be very much appreciated.

**Comment by notmyrealhandle** [comment]
cython 0.27.3.

I don't think this is a cython/fused types bug (or perhaps they have now fixed an earlier bug allowing mismatched argument names in function declarations in pxd and pyx files).  From [here](http://cython.readthedocs.io/en/latest/src/tutorial/pure.html), I read:

"While declarations in a .pyx file must correspond exactly with those of a .pxd file with the same name (and any contradiction results in a compile time error, see pxd files), the untyped definitions in a .py file can be overridden and augmented with static types by the more specific ones present in a .pxd."

Does AS.set_binary_interaction_double() or its equivalent work on what you compile under 3.6?  Or do you get a error saying the argument CAS1 is unknown...

I'll try a PR a bit later today... never done one before.

**Comment by notmyrealhandle** [comment]
The file produced from:

git format-patch master --stdout > [AbstractState.patch](https://gist.github.com/notmyrealhandle/30b72f299d6962f10e41fbfa54a139c9)

HTH.

**Comment by ibell** [comment]
That's cool, but a pull request is far better.  With a pull request we can easily review the changes.  You can even do all this in the browser - fork the CoolProp repo, make the changes, make a pull request.  Please also see https://github.com/CoolProp/CoolProp/wiki/Contributing%3A-git-development-workflow
